sudo: false
language: php
services:
  - docker
matrix:
  fast_finish: true
  include:
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'
    env: SNIFF=1
  - php: '7.2'
  - php: nightly
  allow_failures:
  - php: '5.6'
  - php: nightly
before_install:
- if [[ "$SNIFF" == "1" ]]; then docker pull domw/phpcs; fi
- phpenv rehash
script:
- find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- if [[ "$SNIFF" == "1" ]]; then docker run --rm -v $PWD:/code:ro domw/phpcs phpcs --colors --standard=Magento2 --report=full,summary,gitblame --extensions=php,phtml ./; fi
